version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar Railway
          command: |
            npm install -g @railway/cli
      - run:
          name: Login Railway (browserless)
          command: |
            railway login --browserless <<< $RAILWAY_TOKEN
      - run:
          name: Desplegar API en Railway
          command: |
            cd bankchurn-api
            railway up --service=CI-CD --detach

workflows:
  build-and-test:
    jobs:
      - build-and-deploy
